// <auto-generated />
namespace ForumModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TopicNewRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TopicNewRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201512242108531_TopicNewRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
